# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/syricoff/PycharmProjects/SKeyPassword/src/SKeyPassword/ui/Add_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_password(object):
    def setupUi(self, Add_password):
        Add_password.setObjectName("Add_password")
        Add_password.setWindowModality(QtCore.Qt.ApplicationModal)
        Add_password.resize(533, 244)
        self.gridLayout = QtWidgets.QGridLayout(Add_password)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_application = QtWidgets.QLabel(Add_password)
        self.label_application.setObjectName("label_application")
        self.gridLayout_2.addWidget(self.label_application, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(Add_password)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.gridLayout_2.addWidget(self.password, 3, 1, 1, 1)
        self.label_category = QtWidgets.QLabel(Add_password)
        self.label_category.setObjectName("label_category")
        self.gridLayout_2.addWidget(self.label_category, 0, 0, 1, 1)
        self.login = QtWidgets.QLineEdit(Add_password)
        self.login.setPlaceholderText("")
        self.login.setObjectName("login")
        self.gridLayout_2.addWidget(self.login, 2, 1, 1, 1)
        self.app = QtWidgets.QComboBox(Add_password)
        self.app.setEditable(True)
        self.app.setCurrentText("")
        self.app.setPlaceholderText("")
        self.app.setDuplicatesEnabled(False)
        self.app.setFrame(True)
        self.app.setObjectName("app")
        self.gridLayout_2.addWidget(self.app, 1, 1, 1, 1)
        self.category = QtWidgets.QComboBox(Add_password)
        self.category.setEditable(True)
        self.category.setPlaceholderText("")
        self.category.setObjectName("category")
        self.gridLayout_2.addWidget(self.category, 0, 1, 1, 1)
        self.label_login = QtWidgets.QLabel(Add_password)
        self.label_login.setObjectName("label_login")
        self.gridLayout_2.addWidget(self.label_login, 2, 0, 1, 1)
        self.label_password = QtWidgets.QLabel(Add_password)
        self.label_password.setObjectName("label_password")
        self.gridLayout_2.addWidget(self.label_password, 3, 0, 1, 1)
        self.errors = QtWidgets.QLabel(Add_password)
        self.errors.setStyleSheet("color: rgb(255, 0, 0)")
        self.errors.setText("")
        self.errors.setObjectName("errors")
        self.gridLayout_2.addWidget(self.errors, 4, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Add_password)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Add_password)
        self.buttonBox.accepted.connect(Add_password.accept) # type: ignore
        self.buttonBox.rejected.connect(Add_password.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Add_password)

    def retranslateUi(self, Add_password):
        _translate = QtCore.QCoreApplication.translate
        Add_password.setWindowTitle(_translate("Add_password", "Добавить пароль"))
        self.label_application.setText(_translate("Add_password", "Приложение"))
        self.label_category.setText(_translate("Add_password", "Категория"))
        self.label_login.setText(_translate("Add_password", "Логин"))
        self.label_password.setText(_translate("Add_password", "Пароль"))
