# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/syricoff/PycharmProjects/SKeyPassword/ui/Add_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_password(object):
    def setupUi(self, Add_password):
        Add_password.setObjectName("Add_password")
        Add_password.setWindowModality(QtCore.Qt.ApplicationModal)
        Add_password.resize(400, 225)
        self.gridLayout = QtWidgets.QGridLayout(Add_password)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_category = QtWidgets.QLabel(Add_password)
        self.label_category.setObjectName("label_category")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_category)
        self.category = QtWidgets.QComboBox(Add_password)
        self.category.setEditable(True)
        self.category.setPlaceholderText("")
        self.category.setObjectName("category")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.category)
        self.label_application = QtWidgets.QLabel(Add_password)
        self.label_application.setObjectName("label_application")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_application)
        self.application = QtWidgets.QComboBox(Add_password)
        self.application.setEditable(True)
        self.application.setCurrentText("")
        self.application.setPlaceholderText("")
        self.application.setFrame(True)
        self.application.setObjectName("application")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.application)
        self.label_login = QtWidgets.QLabel(Add_password)
        self.label_login.setObjectName("label_login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_login)
        self.login = QtWidgets.QLineEdit(Add_password)
        self.login.setPlaceholderText("")
        self.login.setObjectName("login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.login)
        self.label_password = QtWidgets.QLabel(Add_password)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.password = QtWidgets.QLineEdit(Add_password)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Add_password)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Add_password)
        self.buttonBox.accepted.connect(Add_password.accept) # type: ignore
        self.buttonBox.rejected.connect(Add_password.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Add_password)

    def retranslateUi(self, Add_password):
        _translate = QtCore.QCoreApplication.translate
        Add_password.setWindowTitle(_translate("Add_password", "Добавить пароль"))
        self.label_category.setText(_translate("Add_password", "Категория"))
        self.label_application.setText(_translate("Add_password", "Приложение"))
        self.label_login.setText(_translate("Add_password", "Логин"))
        self.label_password.setText(_translate("Add_password", "Пароль"))
